# Generated by Django 5.0.6 on 2024-06-07 09:49

import django.db.models.deletion
import ideas.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to=ideas.models.upload_to, verbose_name="Picture"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_ideas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="category_ideas",
                        to="categories.category",
                        verbose_name="Categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Idea",
                "verbose_name_plural": "Ideas",
            },
        ),
        migrations.AddConstraint(
            model_name="idea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("author", None), _negated=True),
                fields=("title",),
                name="unique_titles_for_each_author",
            ),
        ),
        migrations.AddConstraint(
            model_name="idea",
            constraint=models.CheckConstraint(
                check=models.Q(("title__iregex", "^\\S.*\\S$")),
                name="title_has_no_leading_and_trailing_whitespaces",
            ),
        ),
    ]
